# using { RoundSystem }
# using { /Fortnite.com }
# using { /Fortnite.com/Characters }
# using { /Fortnite.com/Devices }
# using { /Fortnite.com/Game }
# using { /UnrealEngine.com/JSON }
# using { /UnrealEngine.com/Temporary/Diagnostics }
# using { /Verse.org/Colors }
# using { /Verse.org/Simulation }


# stats_handler<public> := class(creative_device):

#     OnBegin<override>()<suspends>:void=
#         Print("Hello Worlddd")


